### ISSUE TITLE
How do you handle deletion, removing an element from an array or object?

### ISSUE THREAD

**Issue by slightlytyler** [dustingetz/update-in#6]
This library is my pick for immutable manipulations but I'm still using lodash's `without` and `omit` for these functions. Can these be accomplished with the tools in this library?

**Comment by dustingetz** [comment]
Dissoc and assoc are what I think you are looking for, they are documented
in the read me. They went in very recently.

**Comment by slightlytyler** [comment]
Ah yes I'm blind (:
